# Generated by Django 6.0.6 on 2026-07-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.URLField(blank=True, verbose_name='cover image'),
        ),
    ]
