# Generated by Django 6.0.6 on 2026-07-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='订阅时间')),
            ],
            options={
                'verbose_name': '订阅者',
                'verbose_name_plural': '订阅者',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='article',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='定时发布时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档'), ('scheduled', '定时发布')], default='draft', max_length=16, verbose_name='状态'),
        ),
    ]
