# Generated by Django 6.0.6 on 2026-07-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_notification_sent'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-created_at'], name='articles_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['scheduled_at'], name='articles_scheduled_idx'),
        ),
    ]
