# Generated by Django 6.0.6 on 2026-07-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendlink',
            options={'ordering': ['sort_order'], 'verbose_name': '友情链接', 'verbose_name_plural': '友情链接'},
        ),
        migrations.RemoveField(
            model_name='friendlink',
            name='created_at',
        ),
        migrations.AddField(
            model_name='friendlink',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='sort order'),
        ),
    ]
