# Generated by Django 6.0.6 on 2026-07-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='author_email',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='author_name',
        ),
    ]
